language: node_js
node_js:
- '10'
- '12'
- '14'
deploy:
  provider: npm
  email: julian@dotcore.co.il
  api_key:
    secure: PnZGkV8lXIqcizrhlCLKFKAQmNuWllAdgPHX6+Aqr5hBFSNu5/F72YnEiTmtSmpSQJQ1nPH4o/L5weydrwyQkXaMsr7wKKketlZKvL7r7RbORlqqbJ7LHNjTUXI3ZudnuLYAzBiFYrDBAqkDAc8+9YKKtbNki2qMlzfsI4bSB0SJQ/4wnWSY1cCzsYy6yMsDqCnZvyfbu19a1tk+/XtOVRXM6gU0sQRzH+Zt/TcbQc6CqMvki1RakUdmvuhOcj9+OC6C5a3y76iV7BAVaDTUQ8ovC3BLljhMXG2hblwRW3V5cX1HwjlGIGETtGdjsH5KLR0K+Aqr3J/A+ptlIfGGDe8v67J474bzduNMlXM0hqIBX+GL6f0FaSz2RsJPlZbL/6KF4cAR5QP26zvqXlg3nTijoqtuYWCEdnBGObMGC38CBgUvo2GGyyHTLj73p90KLojhlx3D2IfwtY9JyNxfXLrP0VjIkyVbiMz9ZWArlPcWYOxHTGDCjValLjTMS4ngmrrkJ+2MI78c5Lqhi92eWrsCWZgPB1DPRSYcbF5X++IofcohYT3Wm0fcNPwAhMO/iz+qUc1OM59YXlA1JvUD0rFAQAm96nmC65yZl2lHpI8eMFEKnYi7RjbPR25Vc6tbZZsUIwly5hyrapCITtwmC5Uh1UFKkqvvSmPMNI/uNag=
  on:
    tags: true
    repo: dotcore64/redis-hsetex
  skip_cleanup: 'true'
services:
- redis-server
